name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        ruby_version: [ruby-head, '3.1', '3.0', '2.7']
        rails_version: [edge, '7.0', '6.1']

        include:
          - ruby_version: '2.6'
            rails_version: '6.1'

          - ruby_version: '3.0'
            rails_version: '6.0'
          - ruby_version: '2.7'
            rails_version: '6.0'
          - ruby_version: '2.6'
            rails_version: '6.0'

          - ruby_version: '2.7'
            rails_version: '5.2'
          - ruby_version: '2.6'
            rails_version: '5.2'

          - ruby_version: '2.6'
            rails_version: '5.1'

          - ruby_version: '2.6'
            rails_version: '5.0'

    runs-on: ubuntu-18.04

    env:
      RAILS_VERSION: ${{ matrix.rails_version }}

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
          bundler: ${{ (startsWith(matrix.rails_version, '4.') || startsWith(matrix.rails_version, '3.')) && '1' || '2' }}
        continue-on-error: ${{ (matrix.ruby_version == 'ruby-head') || (matrix.allow_failures == 'true') }}

      - run: bundle exec rake
        continue-on-error: ${{ (matrix.ruby_version == 'ruby-head') || (matrix.rails_version == 'edge') || (matrix.allow_failures == 'true') }}
